---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: end-to-end
  namespace: open-feature-demo
spec:
  flagSpec:
    flags:
      new-welcome-message:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "on"
      hex-color:
        state: ENABLED
        variants:
          red: c05543
          green: 2f5230
          blue: 0d507b
          yellow: yellow
        defaultVariant: blue
      fib-algo:
        state: ENABLED
        variants:
          recursive: recursive
          memo: memo
          loop: loop
          binet: binet
        defaultVariant: recursive
        "targeting":
          {
            "if":
              [{ "in": ["@faas.com", { "var": ["email"] }] }, "binet", null],
          }
